attention_dim: 64
batch_size: 64
dropout: 0.3
early_stopping_patience: 10
epochs: 10
hidden_size: 128
input_dim: 3
learning_rate: 0.001
lr_scheduler_factor: 0.5
lr_scheduler_patience: 5
model: bilstm_attention
num_classes: 6
num_layers: 2
seed: 42
selected_channels:
- 3
- 4
- 5
test_path: data/processed/UCI_HAR/UCI-HAR_test.npz
train_path: data/processed/UCI_HAR/UCI-HAR_train.npz
val_path: data/processed/UCI_HAR/UCI-HAR_val.npz
