#!/usr/bin/env python
"""Smoke test for MotionShield Bi‑LSTM + Temporal Attention model.

Validates data pipeline, model forward/backward passes, gradients, and checkpointing on CPU.
"""

import sys
import argparse
import yaml
import torch
import numpy as np
from pathlib import Path
# Ensure repo root is in PYTHONPATH for ml package imports
sys.path.append(str(Path(__file__).resolve().parents[1]))
from ml.models import get_model

def load_train_data(npz_path: Path):
    data = np.load(npz_path)
    return data["windows"], data["labels"]

def count_parameters(model: torch.nn.Module) -> int:
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

def check_nan_inf(tensor, name: str):
    if torch.isnan(tensor).any():
        return f"{name} contains NaN"
    if torch.isinf(tensor).any():
        return f"{name} contains Inf"
    return None

def main():
    parser = argparse.ArgumentParser(description="MotionShield ML smoke test")
    parser.add_argument("--config", type=str, required=True, help="Path to experiment YAML config")
    args = parser.parse_args()

    cfg = yaml.safe_load(Path(args.config).read_text())
    # Load training NPZ (generated by dataset preparation)
    train_npz = Path("data/processed/UCI_HAR/UCI-HAR_train.npz")
    windows, labels = load_train_data(train_npz)
    input_shape = windows.shape  # (N, T, C)
    batch_size = 2

    model_cfg = {
        "input_dim": input_shape[2],
        "hidden_size": cfg.get("hidden_size", 128),
        "num_layers": cfg.get("num_layers", 2),
        "num_classes": cfg.get("num_classes", int(labels.max()) + 1),
        "dropout": cfg.get("dropout", 0.3),
        "attention_dim": cfg.get("attention_dim", 64),
    }
    model = get_model(cfg["model"], **model_cfg).to(torch.device("cpu"))

    X = torch.tensor(windows, dtype=torch.float32)
    y = torch.tensor(labels, dtype=torch.long)
    dataset = torch.utils.data.TensorDataset(X, y)
    loader = torch.utils.data.DataLoader(dataset, batch_size=batch_size, shuffle=False)

    # One forward pass
    model.train()
    xb, yb = next(iter(loader))
    logits = model(xb)
    forward_issue = check_nan_inf(logits, "Logits")
    loss_fn = torch.nn.CrossEntropyLoss()
    loss = loss_fn(logits, yb)
    loss_issue = check_nan_inf(loss, "Loss")

    # Backward pass
    loss.backward()
    grad_nan = []
    grad_inf = []
    for name, p in model.named_parameters():
        if p.grad is not None:
            if torch.isnan(p.grad).any():
                grad_nan.append(name)
            if torch.isinf(p.grad).any():
                grad_inf.append(name)

    param_count = count_parameters(model)

    # Checkpoint
    ckpt_dir = Path("models/smoke_test")
    ckpt_dir.mkdir(parents=True, exist_ok=True)
    ckpt_path = ckpt_dir / "smoke_test_checkpoint.pth"
    torch.save({"model_state_dict": model.state_dict(), "config": model_cfg}, ckpt_path)

    # Reload
    fresh = get_model(cfg["model"], **model_cfg).to(torch.device("cpu"))
    fresh.load_state_dict(torch.load(ckpt_path, map_location="cpu")["model_state_dict"])
    fresh.eval()
    with torch.no_grad():
        fresh_logits = fresh(xb)
    reload_ok = fresh_logits.shape == logits.shape

    # Reporting
    import sys
    print("""========================================
MotionShield ML SMOKE TEST
========================================""")
    print(f"Python: {sys.version.split()[0]}")
    print(f"PyTorch: {torch.__version__}")
    print(f"Device: cpu")
    print()
    print("Dataset:")
    print(f"  Input shape: {input_shape}")
    print(f"  Batch shape: {xb.shape}")
    print(f"  Number of classes: {model_cfg['num_classes']}")
    print(f"  Number of channels: {input_shape[2]}")
    print()
    print("Model:")
    print(f"  Architecture: {cfg['model']}")
    print(f"  Trainable parameters: {param_count}")
    print()
    print("Forward pass:")
    print(f"  Output shape: {logits.shape}")
    print(f"  Forward NaN: {forward_issue or 'None'}")
    print(f"  Forward Inf: {forward_issue and 'None' or 'None'}")
    print()
    print("Loss:")
    print(f"  Loss value: {loss.item():.6f}")
    print(f"  Loss NaN: {loss_issue or 'None'}")
    print(f"  Loss Inf: {loss_issue and 'None' or 'None'}")
    print()
    print("Backward pass:")
    print(f"  Completed: True")
    print(f"  Gradient NaN: {', '.join(grad_nan) if grad_nan else 'None'}")
    print(f"  Gradient Inf: {', '.join(grad_inf) if grad_inf else 'None'}")
    print()
    print("Checkpoint:")
    print(f"  Saved: {ckpt_path.exists()}")
    print(f"  Reloaded: {reload_ok}")
    print()
    final = (forward_issue is None and loss_issue is None and not grad_nan and not grad_inf and reload_ok)
    print(f"FINAL RESULT: {'PASS' if final else 'FAIL'}")

if __name__ == "__main__":
    main()
