#!/usr/bin/env python
"""Training script for MotionShield models with full configurability.

Features:
- YAML config with hyper‑parameters, early stopping, LR scheduler, random seed.
- Automatic device detection (CUDA → GPU, MPS → Apple GPU, else CPU).
- Loads predefined NPZ splits (train/val/test) generated by prepare_dataset.py.
- Saves training‑fitted scaler, configuration, label mapping, model metadata, training history, and checkpoints.
- Supports custom output directory via --output_dir (default: models/smartphone_har).
"""

import argparse
import json
import yaml
import torch
import random
import numpy as np
import joblib
import os
import time
from pathlib import Path
from torch.utils.tensorboard import SummaryWriter

# Model factory
import sys, os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from ml.models import get_model


def set_random_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def load_data(npz_path: Path):
    data = np.load(npz_path)
    windows = data["windows"]  # (n_samples, seq_len, n_features)
    labels = (data["labels"] - 1).astype(np.int64)  # convert to 0‑based class indices
    subject_ids = data.get("subject_ids")  # optional for LO‑SO split
    return windows, labels, subject_ids


def get_device():
    if torch.cuda.is_available():
        device = torch.device("cuda")
        print(f"Device: CUDA – {torch.cuda.get_device_name(0)}")
    elif getattr(torch.backends, "mps", None) and torch.backends.mps.is_available():
        device = torch.device("mps")
        print("Device: Apple MPS (GPU)")
    else:
        device = torch.device("cpu")
        print("Device: CPU")
    return device


def main():
    parser = argparse.ArgumentParser(description="Train a MotionShield model")
    parser.add_argument("--config", type=str, required=True, help="Path to experiment YAML config")
    parser.add_argument(
        "--output_dir",
        type=str,
        default="models/smartphone_har",
        help="Directory to store model artifacts",
    )
    args = parser.parse_args()

    cfg = yaml.safe_load(Path(args.config).read_text())
    set_random_seed(cfg.get("seed", 42))
    device = get_device()

    # Ensure output directory exists
    model_dir = Path(args.output_dir)
    model_dir.mkdir(parents=True, exist_ok=True)

    # Load predefined split files
    train_npz = Path(cfg.get('train_path'))
    val_npz = Path(cfg.get('val_path'))
    test_npz = Path(cfg.get('test_path'))
    train_windows, train_labels, train_subjects = load_data(train_npz)
    val_windows, val_labels, val_subjects = load_data(val_npz)
    test_windows, test_labels, test_subjects = load_data(test_npz)

    # Verify channel order from training metadata
    meta_path = Path("data/processed/UCI_HAR/metadata_train.json")
    meta = json.load(open(meta_path))
    expected_channels = ["acc_x", "acc_y", "acc_z", "gyro_x", "gyro_y", "gyro_z"]
    assert meta["channels"] == expected_channels, f"Channel order mismatch: {meta['channels']}"

    # Verify input shape
    assert train_windows.shape[1:] == (128, 6), f"Train shape mismatch: {train_windows.shape}"
    assert val_windows.shape[1:] == (128, 6), f"Val shape mismatch: {val_windows.shape}"
    assert test_windows.shape[1:] == (128, 6), f"Test shape mismatch: {test_windows.shape}"

    # ---- Scaling (fit on training data only) ----
    flat = train_windows.reshape(-1, train_windows.shape[2])
    means = flat.mean(axis=0)
    stds = flat.std(axis=0)
    stds[stds == 0] = 1.0
    def scale(arr):
        f = arr.reshape(-1, arr.shape[2])
        s = (f - means) / stds
        return s.reshape(arr.shape)
    train_windows = scale(train_windows)
    val_windows = scale(val_windows)
    test_windows = scale(test_windows)

    # Save scaler and configuration artifacts
    scaler_path = model_dir / "scaler.pkl"
    joblib.dump({"means": means, "stds": stds}, scaler_path)
    cfg_path = model_dir / "config.yaml"
    with cfg_path.open("w") as f:
        yaml.safe_dump(cfg, f)
    # Save label mapping (from metadata)
    labels_path = model_dir / "labels.json"
    with labels_path.open("w") as f:
        json.dump(meta.get("label_mapping", {}), f, indent=2)
    # Save a copy of the full metadata for reference
    meta_out_path = model_dir / "model_metadata.json"
    with meta_out_path.open("w") as f:
        json.dump(meta, f, indent=2)

    # Convert data to tensors
    X_train = torch.tensor(train_windows, dtype=torch.float32).to(device)
    y_train = torch.tensor(train_labels, dtype=torch.long).to(device)
    X_val = torch.tensor(val_windows, dtype=torch.float32).to(device)
    y_val = torch.tensor(val_labels, dtype=torch.long).to(device)
    X_test = torch.tensor(test_windows, dtype=torch.float32).to(device)
    y_test = torch.tensor(test_labels, dtype=torch.long).to(device)

    input_dim = X_train.shape[2]

    # Pre‑training audit
    print("=== PRE-TRAINING AUDIT ===")
    print(f"Train subjects ({len(set(train_subjects))}): {sorted(set(train_subjects))}")
    print(f"Val subjects   ({len(set(val_subjects))}): {sorted(set(val_subjects))}")
    print(f"Test subjects  ({len(set(test_subjects))}): {sorted(set(test_subjects))}")
    print(f"Overlap train&val: {set(train_subjects).intersection(set(val_subjects))}")
    print(f"Overlap train&test: {set(train_subjects).intersection(set(test_subjects))}")
    print(f"Overlap val&test:   {set(val_subjects).intersection(set(test_subjects))}")
    print(f"NaN in train windows: {np.isnan(train_windows).any()}")
    print(f"Inf in train windows: {np.isinf(train_windows).any()}")
    print("=== END AUDIT ===")

    # Model configuration
    model_cfg = {
        "input_dim": input_dim,
        "num_classes": cfg.get("num_classes", 6),
        "hidden_size": cfg.get("hidden_size", 128),
        "num_layers": cfg.get("num_layers", 2),
        "dropout": cfg.get("dropout", 0.3),
        "attention_dim": cfg.get("attention_dim", 64),
    }
    model = get_model(cfg["model"], **model_cfg).to(device)

    criterion = torch.nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=cfg.get("learning_rate", 1e-3))
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="min",
        factor=cfg.get("lr_scheduler_factor", 0.5),
        patience=cfg.get("lr_scheduler_patience", 5)
    )

    early_patience = cfg.get("early_stopping_patience", 10)
    best_val_loss = float("inf")
    epochs_no_improve = 0

    # TensorBoard logging
    log_dir = Path("logs") / Path(args.config).stem
    writer = SummaryWriter(str(log_dir))

    epochs = cfg.get("epochs", 30)
    batch_size = cfg.get("batch_size", 64)

    # Training history container
    history = {
        "epochs": [],
        "train_loss": [],
        "train_accuracy": [],
        "val_loss": [],
        "val_accuracy": [],
        "learning_rate": [],
    }

    for epoch in range(1, epochs + 1):
        # ----- Training -----
        model.train()
        train_dataset = torch.utils.data.TensorDataset(X_train, y_train)
        train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
        train_loss_total = 0.0
        correct = 0
        total = 0
        for xb, yb in train_loader:
            optimizer.zero_grad()
            outputs = model(xb)
            loss = criterion(outputs, yb)
            loss.backward()
            optimizer.step()
            train_loss_total += loss.item() * xb.size(0)
            preds = outputs.argmax(dim=1)
            correct += (preds == yb).sum().item()
            total += yb.size(0)
        train_loss = train_loss_total / len(train_dataset)
        train_acc = correct / total if total else 0.0

        # ----- Validation -----
        model.eval()
        with torch.no_grad():
            val_dataset = torch.utils.data.TensorDataset(X_val, y_val)
            val_loader = torch.utils.data.DataLoader(val_dataset, batch_size=batch_size)
            val_loss_total = 0.0
            correct = 0
            total = 0
            for xb, yb in val_loader:
                outputs = model(xb)
                loss = criterion(outputs, yb)
                val_loss_total += loss.item() * xb.size(0)
                preds = outputs.argmax(dim=1)
                correct += (preds == yb).sum().item()
                total += yb.size(0)
            val_loss = val_loss_total / len(val_dataset)
            val_acc = correct / total if total else 0.0

        # Log to TensorBoard & history
        writer.add_scalar("Loss/train", train_loss, epoch)
        writer.add_scalar("Loss/val", val_loss, epoch)
        writer.add_scalar("Accuracy/val", val_acc, epoch)
        writer.add_scalar("LearningRate", optimizer.param_groups[0]["lr"], epoch)

        history["epochs"].append(epoch)
        history["train_loss"].append(train_loss)
        history["train_accuracy"].append(train_acc)
        history["val_loss"].append(val_loss)
        history["val_accuracy"].append(val_acc)
        history["learning_rate"].append(optimizer.param_groups[0]["lr"])

        print(f"Epoch {epoch}/{epochs} – Train Loss: {train_loss:.4f} – Train Acc: {train_acc:.4f} – Val Loss: {val_loss:.4f} – Val Acc: {val_acc:.4f}")

        # Scheduler step
        scheduler.step(val_loss)

        # Early stopping & checkpointing
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            epochs_no_improve = 0
            ckpt_path = model_dir / "best_checkpoint.pth"
            torch.save({
                "epoch": epoch,
                "model_state_dict": model.state_dict(),
                "optimizer_state_dict": optimizer.state_dict(),
                "val_loss": val_loss,
                "config": cfg,
            }, ckpt_path)
            print(f"Saved best checkpoint to {ckpt_path}")
        else:
            epochs_no_improve += 1
            if epochs_no_improve >= early_patience:
                print(f"Early stopping triggered after {epoch} epochs.")
                break

    # Save final model state dict
    final_path = model_dir / "model.pth"
    torch.save(model.state_dict(), final_path)
    print(f"Saved final model to {final_path}")

    # Save training history JSON
    history_path = model_dir / "training_history.json"
    with history_path.open("w") as f:
        json.dump(history, f, indent=2)

    writer.close()

if __name__ == "__main__":
    main()
